FROM node:23.8.0-alpine

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm ci

# Copier le code source
COPY . .
# Pour avoir le .env de développement
RUN cp .env.development .env

# Générer le client Prisma
RUN npx prisma generate

# Exposer le port
EXPOSE 3000

# Healthcheck simple pour le dev
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/test || exit 1

# Utiliser tsx watch pour le hot reload
CMD ["npx", "tsx", "watch", "src/index.ts"]